2023-08-21 10:13:47,470 ERROR {result}
Traceback (most recent call last):
  File "C:\Users\Andrew\PycharmProjects\homework\hw_17\log_file.py", line 9, in <module>
    print(count[4])
IndexError: list index out of range
2023-08-21 10:14:24,320 ERROR {result}
Traceback (most recent call last):
  File "C:\Users\Andrew\PycharmProjects\homework\hw_17\log_file.py", line 9, in <module>
    print(count[4])
IndexError: list index out of range
2023-08-21 10:14:24,321 ERROR {result}
Traceback (most recent call last):
  File "C:\Users\Andrew\PycharmProjects\homework\hw_17\log_file.py", line 15, in <module>
    print(count1[6])
KeyError: 6
2023-08-21 10:14:57,255 ERROR {result}
Traceback (most recent call last):
  File "C:\Users\Andrew\PycharmProjects\homework\hw_17\log_file.py", line 9, in <module>
    print(count[4])
IndexError: list index out of range
2023-08-21 10:14:57,257 DEBUG {result}
Traceback (most recent call last):
  File "C:\Users\Andrew\PycharmProjects\homework\hw_17\log_file.py", line 15, in <module>
    print(count1[6])
KeyError: 6
